capplets/keybindings/01-desktop-key.xml.in
provided additional "logout" key bindings
part of https://github.com/mate-desktop/mate-settings-daemon/pull/76
fix for https://github.com/mate-desktop/mate-control-center/issues/107
=> logout key bindings

capplets/mouse/mate-mouse-properties.c, capplets/mouse/mate-mouse-properties.ui
fixes https://github.com/mate-desktop/mate-desktop/issues/178
=> touchpad settings: add option to enable/disable touchpad

capplets/about-me/eel-alert-dialog.c, capplets/about-me/mate-about-me-password.c, capplets/about-me/mate-about-me.c, capplets/appearance/appearance-desktop.c, capplets/appearance/appearance-main.c, capplets/appearance/appearance-style.c, capplets/appearance/appearance-themes.c, capplets/common/file-transfer-dialog.c, capplets/common/theme-thumbnail.c, capplets/keybindings/eggcellrendererkeys.c, capplets/keyboard/mate-keyboard-properties-xkbot.c, capplets/windows/mate-metacity-support.c, capplets/windows/mate-window-properties.c, font-viewer/font-view.c, libslab/app-resizer.c, libslab/app-shell.c, libslab/application-tile.c, libslab/directory-tile.c, libslab/document-tile.c, libslab/search-context-picker.c, libslab/slab-section.c, libslab/system-tile.c, libslab/tile-action.c, typing-break/drw-break-window.c
@raveit65 @lukefromdc please test for any possible issues :smile:
This is not a complete list of deprecations, I think it's only a half... I'll try to fix other ones some time later.
=> fix some deprecations

capplets/about-me/e-image-chooser.c, capplets/common/theme-thumbnail.c
split out from https://github.com/mate-desktop/mate-control-center/pull/220 as this code isn't related to offscreen windows stuff
=> fix some deprecations and build warnings

capplets/common/theme-thumbnail.c
This is simply a rebase of previous PR from @dnk on top of 1.13.0 and for some reasons it works perfect with gtk3.
- no question marks in main window and editor
- all thumbnails are created in one rush after the cache was cleared.
I guess previous commits in master did the magic.
Of course it does not work with gtk2. Here i see everywhere question marks after the cache was cleared.
So we have 2 opportunities:
- fixes the commit for gtk2
- or simply use this for gtk3 only (pretty pefect easy, imo)
@monsta @dnk 
Please test and maybe you have a idea why this doen't work with gtk2
Note, i've reverted the GTKSTOCK_OPEN lines because this remove the open icon,
and for the deprecated gtk_widget_size_request fixes i used a single commit.
=> use offscreen window for previews

capplets/appearance/appearance-font.c
This pull request should be merged after mate-desktop/mate-settings-daemon#147.
=> UI changes to match new default font rendering settings

capplets/about-me/mate-about-me-dialog.ui, capplets/about-me/mate-about-me-fingerprint.ui, capplets/about-me/mate-about-me-password.ui, capplets/accessibility/at-properties/at-enable-dialog.ui, capplets/appearance/data/appearance.ui, capplets/default-applications/mate-default-applications-properties.ui, capplets/keybindings/mate-keybinding-properties.ui, capplets/keyboard/mate-keyboard-properties-a11y-notifications.ui, capplets/keyboard/mate-keyboard-properties-dialog.ui, capplets/keyboard/mate-keyboard-properties-layout-chooser.ui, capplets/keyboard/mate-keyboard-properties-model-chooser.ui, capplets/keyboard/mate-keyboard-properties-options-dialog.ui, capplets/mouse/mate-mouse-properties.ui, capplets/network/mate-network-properties.ui
i hope all looks like before ;-)
=> UI: avoid deprecated widgets

capplets/about-me/eel-alert-dialog.c, capplets/about-me/mate-about-me-password.ui, libslab/directory-tile.c, libslab/document-tile.c, libslab/nameplate-tile.c, libslab/search-bar.c
=> deprecations and warnings

capplets/common/capplet-util.c
=> capplet-util: don't use deprecated gtk_show_uri

capplets/keybindings/eggcellrendererkeys.c
assignment from incompatible pointer type
=> eggcellrendererkeys.c: Fix build warnings:

capplets/appearance/theme-installer.c
This closes #320.
Signed-off-by: Zhang Xianwei <zhang.xianwei8@zte.com.cn>
Hi, please review, thanks:) @raveit65 @monsta @lukefromdc @sc0w
=> Support the theme compression package for installing XZ format

capplets/appearance/theme-installer.c
When ~/.themes/theme-name is existed, reinstalling the same theme will be failed. Add tips when reinstall a existed theme to fix it. This mentioned in #322.
##Steps to reproduce the behaviour##
cd /usr/share/themes (root user)
tar zcvf Menta.tar.gz Menta
Open m-a-p →Choose the "Menta" theme to delete
Click  "Install..." → choose "/usr/share/themes/Menta.tar.gz"
Rechoose "/usr/share/themes/Menta.tar.gz" to install again
It will be failed with tips: Installation for theme "Menta" failed. Can't move directory over directory
@raveit65 @lukefromdc
=> theme-installer.c: add tips when reinstall a existed theme

capplets/common/mate-theme-info.c
Related: mate-desktop/marco/pull/400
=> Scale cursor size for HiDPI when changing themes

capplets/display/display-capplet.ui
=> display-capplet.ui: replace deprecations

capplets/about-me/Makefile.am, capplets/about-me/mate-about-me.c, configure.ac
This is for #360, please review and test, thank you.
=> Accounts service

capplets/keybindings/00-multimedia-key.xml.in
Provided three new key bindings to control volume:
"volume-mute-quiet"
"volume-down-quiet"
"volume-up-quiet"
=> keybindings: Add some key bindings to control volume quietly

capplets/keybindings/00-multimedia-key.xml.in
Provided additional "mic-mute" key binding.
For reference: https://github.com/mate-desktop/mate-settings-daemon/pull/253
=> keybindings: Add a key binding to toggle the microphone's mute status

libslab/app-resizer.c, libslab/app-shell.c, libslab/tile.c
Fixed issue #403
If m-c-c is open, install/uninstall application, m-c-c is crash.
=> Fixed crash when install/remove application.

capplets/display/xrandr-capplet.c
mate-display-properties: capplets/display/xrandr-capplet.c
Note that if you look at `mate-display-properties` executable with `ldd`, you will still find that it depends on `libdbus-glib`. Because I didn't modify Makefile.am, I thought it would be better to migrate all the other code to gdbus and then modify makefile.am.
Please review the code and test it, thank you.
=> Migrate from dbus-glib to GDBus

.travis.yml
Add archlinux build, change some before_scripts, delte the last line after make distcheck.
When after merge #415 , this PR will be ok to use.
=> add archlinux build on travis-ci

.travis.yml
=> [ci] Enable Clang Static Analyzer

capplets/keyboard/mate-keyboard-properties.c, capplets/keyboard/mate-keyboard.desktop.in
Accessibility: Add support for high contrast themes
Before:
After:
=> Use keyboard device icon like in other hardware devices

capplets/appearance/theme-installer.c
=> Fix grammar mistake

font-viewer/font-view.c
Hi,
Just a cosmetic change to begin learning MATE Desktop development.
=> add icon for the font viewer window

capplets/default-applications/mate-da-capplet.c
=> Fix the icon sizes in Preferred Applications selector

capplets/appearance/data/appearance.ui
Add Adjustement to change value by left/right arrows
Fixes #304
=> appearance.ui (cursor size scale)

capplets/default-applications/mate-da-capplet.c, capplets/default-applications/mate-da-capplet.h
=> Add orca to Visual combo box if available

capplets/time-admin/src/main.c, capplets/time-admin/src/time-share.c, capplets/time-admin/src/time-share.h, capplets/time-admin/src/time-zone.c
- Add & enable mnemonic accelerator keys
- Show Save/Close button icons in Time/Date manager window
- Remove DialogAddButtonWithIconName from shares
=> time-admin: shortcuts, images & shared code for buttons

libslab/bookmark-agent.c
Please review and test, thanks.
=> libslab: bookmark-agent.c avoid deprecated g_type_class_add_private

capplets/appearance/appearance-main.c, capplets/common/capplet-util.c, capplets/common/capplet-util.h, capplets/default-applications/mate-da-capplet.c, capplets/keyboard/mate-keyboard-properties.c, capplets/mouse/mate-mouse-properties.c, capplets/network/mate-network-properties.c, capplets/windows/mate-window-properties.c
Fix #445
I don't work on 'time-admin', i have understood than the GUI was not terminated yet.
I plan to purpose another PR when it will be finished.
=>  Add scroll tabs with mouse wheel in severals capplets

capplets/accessibility/at-properties/Makefile.am, capplets/accessibility/at-properties/dm-util.c, capplets/accessibility/at-properties/dm-util.h, capplets/accessibility/at-properties/main.c, gla11y.mk
Please review and test, thanks.
=> support lightdm-gtk-greeter-settings as login preferences program

capplets/accessibility/at-properties/main.c
=> at-properties: migrate from dbus-glib to gdbus

capplets/appearance/appearance-font.c, capplets/appearance/data/appearance.ui
Users can add new fonts for themselves.
=> appearance: add new font for user

capplets/appearance/appearance-font.c
=> appearance: fix memory leak

.travis.yml
don't build from tarballs mate-desktop, mate-menus and mate-settings-daemon
=> [1.22] Travis CI: don't build from tarballs

capplets/appearance/mate-wp-xml.c
~/.xsession-errors 
```
I/O error : No such file or directory
```
=> appearance: remove I/O error on window close

capplets/appearance/appearance-desktop.c
=> appearance: Fix preview in Add Wallpaper dialog

capplets/appearance/appearance-desktop.c, capplets/appearance/appearance-font.c, capplets/appearance/appearance-main.c, capplets/appearance/appearance-style.c, capplets/appearance/appearance-themes.c, capplets/appearance/appearance.h, capplets/appearance/data/appearance.ui, capplets/appearance/theme-save.c
It also fixes the stock deprecations in the UI file.
=> Appearance applet: reduce and simplify the code

capplets/about-me/fingerprint-strings.h, capplets/about-me/mate-about-me-fingerprint.h, capplets/appearance/appearance-desktop.h, capplets/appearance/appearance-font.h, capplets/appearance/appearance-style.h, capplets/appearance/appearance-support.h, capplets/appearance/appearance-themes.h, capplets/appearance/appearance-ui.h, capplets/appearance/appearance.h, capplets/appearance/mate-wp-item.h, capplets/appearance/theme-save.h, capplets/appearance/theme-util.h, capplets/common/gtkrc-utils.h, capplets/display/scrollarea.h, font-viewer/totem-resources.h
Reported by Apache NetBeans IDE:
=> Missing include guards

libslab/bookmark-agent.c
=> bookmark-agent: Function 'bookmark_agent_new' used prior to declaration

capplets/appearance/mate-wp-xml.c
=> i18n: fix an error that prevents showing the wallpaper name

help/C/config-default-apps.xml
Test:
```
$ yelp file:///usr/share/help/C/mate-control-center/config-default-apps.xml 
```
=> help: update default apps

capplets/appearance/appearance-main.c, capplets/appearance/appearance-ui.c, capplets/appearance/appearance.h
=> appearance: Type column in GtkFileChooser requires gtk 3.24.12

libslab/bookmark-agent.c, libslab/bookmark-agent.h
=> bookmark-agent: fix backward compatibility with glib < 2.66

capplets/keybindings/mate-keybinding-properties.c
```
CFLAGS="-ggdb3 -O0 -fsanitize=address" LDFLAGS="-fsanitize=address" ./autogen.sh --prefix=/usr && make && sudo make install
```
```
Direct leak of 165758 byte(s) in 4278 object(s) allocated from:
#0 0x7fa6035aa93f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7fa601cdb4df in g_malloc ../glib/gmem.c:106
#2 0x7fa601cdb822 in g_malloc_n ../glib/gmem.c:344
#3 0x7fa601cfde35 in g_strdup ../glib/gstrfuncs.c:361
#4 0x7fa601e1d016 in value_lcopy_string ../gobject/gvaluetypes.c:313
#5 0x7fa601df4559 in g_object_get_valist ../gobject/gobject.c:2659
#6 0x7fa601df4990 in g_object_get ../gobject/gobject.c:2754
#7 0x40a294 in key_match /home/robert/builddir.gcc/mate-control-center/capplets/keybindings/mate-keybinding-properties.c:429
#8 0x7fa602a98300 in gtk_tree_model_foreach_helper …
```
=> keybindings: fix memory leak

capplets/windows/window-properties.ui
Fix https://github.com/mate-desktop/mate-control-center/issues/785
Tested by rebuilding Mate 1.26 Debian source package.
=> Update window layout
