libslab/slab-mate-util.c

should be used after https://github.com/mate-desktop/mate-desktop/pull/167 is applied

[1.8] libslab: do not reap child when launching desktop items

---

capplets/keyboard/mate-keyboard-properties-layout-chooser.ui
capplets/keyboard/mate-keyboard-properties-model-chooser.ui
capplets/keyboard/mate-keyboard-properties-options-dialog.ui
capplets/mouse/mate-mouse-properties.ui

- this fixes unusable keyboard properties window
- reduce size of mouse properties window

UI GTK3: fix keyboard and mouse properties windows

---

capplets/appearance/appearance-support.c

A new compiz just landed in Ubuntu 15.10 which pretty much broke the MATE integration. Since metacity 3.1.6 the `theme` setting in `org.gnome.desktop.wm.preferences` is deprecated and ignored. 
Metacity >=3.16 now reads the `theme` from `org.gnome.metacity` although some other configuration is still accessed from `org.gnome.desktop.wm.preferences`
The pull request write the `theme` to `org.gnome.metacity` as well as the legacy location.

Add theme changing support for metacity >= 3.16

---

capplets/keyboard/mate-keyboard-properties-xkblt.c

keyboard properties: don't set parent widget on show layout dialog

---

capplets/display/xrandr-capplet.c

We must set the refresh rate, not read current refresh rate when it is changed in combobox.

Bugfix: Changing refresh rate doens't work

---

capplets/appearance/appearance-themes.c

When closing, function `theme_selection_changed_cb()` is called. And at that time, `data->ui` is no longer a valid GtkBuilder. So just do nothing on closing.
This patch fixes #200

appearance: Fix segmentation fault on closing

---

libslab/app-resizer.c

This fixes following issue: https://github.com/mate-desktop/mate-control-center/issues/208

Fix for incorect area size with hidpi

---

capplets/common/wm-common.c
typing-break/main.c

Use gdk_x11_get_xatom_by_name (), and take advantage of GDK's caches.

Use GDK convenient function

---

libslab/app-resizer.c
libslab/app-resizer.h
libslab/app-shell.c
libslab/app-shell.h
libslab/nameplate-tile.c
libslab/search-bar.c
libslab/search-bar.h
libslab/search-context-picker.c
libslab/shell-window.c
libslab/slab-section.c
libslab/slab-section.h

and fix deprecated usage of GtkHBox and GtkVBox in GTK+3 build
@flexiondotorg @sunweaver @gnugr: this commit changes the public interface of libslab in both GTK+ builds (due to transition of classes' parents and/or members from GtkVBox to GtkBox). So a rebuild of ```gnome-main-menu``` might be needed after this. However, I found out that g-m-m crashes with mate-panel 1.12 anyway, no matter if I rebuild it or not...

libslab: use GtkBox instead of GtkVBox in both GTK+ builds

---

capplets/mouse/mate-mouse-properties.c
capplets/mouse/mate-mouse-properties.ui

This is to be used with https://github.com/mate-desktop/mate-settings-daemon/pull/161.
I didn't add touchpad handedness setting there yet as it's set to follow mouse setting by default. Or maybe because I'm lazy :smile:
@clefebvre @flexiondotorg @raveit65 @XRevan86 @sc0w @lukefromdc
Please test it guys if you can.

mouse: add separate touchpad motion settings on touchpad tab

---

capplets/appearance/appearance-style.c

Fix list-specific live updates, like whether the theme can be deleted, or the available cursor sizes for the current theme.
This got lost in GSettings migration in b3e27b1d6a0f11c5835f5829bac3861e2147b17e.  The initial value update was restored in 070e7cb765a788c8e27ff3615d3ed36981d3518d.
Note: as signals handlers are called in the order they are registered, the specific one will run after the generic one, so the generic updates will have been applied.
----
The leaks fix is unrelated, and can be split out it you want.

Fix live updating of some theme interface elements

---

capplets/common/file-transfer-dialog.c

I am not sure about this one as i couldn't trigger the gui for it.
Code says it is in capplets/appearance/theme-installer.c .
Any way, this is last GtkTable in our code which is possible to port to GtkGrid.
I guess the rest of GtkTable widgets in m-c-c needs a complete rewrite of the code, as for widgets like gtk_table_resize or gtk_table_get_size there is no replacement in GtkGrid.

file-transfer-dialog: port to GtkGrid

---

capplets/common/theme-thumbnail.c
capplets/keyboard/mate-keyboard-properties-xkbot.c

Indeed this is the close button in the thumbnail, so you need to clear the thumbnail cache for testing
~.cache/thumbnails/normal
~.cache/thumbnails/fail

avoid deprecated GtkAlignment

---

capplets/appearance/appearance-support.c

This pull request adds support for switching themes for Metacity >= 3.20, when the schema changed again. Support for Metacity <= 3.318 has been retained for those needing it. The keys previously used by Metacity >= 3.12 are still relevant for use by GNOME3.

Add support for switching themes on Metacity >= 3.20.

---

capplets/keybindings/mate-keybinding-properties.ui

Also remove an unnecessary intermediate box, we can pack in the grid
directly.
Fix for breakage introduced in #274.

keybindings: Fix and add mnemonics in the custom command dialog

---

libslab/bookmark-agent.c

It seems that gnome(mate)-main-menu is the only application which use the bookmark path from libslab.
https://github.com/mate-desktop/mate-control-center/blob/master/libslab/bookmark-agent.c#L26
So this isn't really testable.
I changed some other paths which were wrong too.
Please review.

libslab bookmark-agent: fix some xdg paths

---

libslab/mate-utils.c
libslab/themed-icon.c

fixes loading app icons from /usr/share/pixmaps when the icon theme
doesn't have an icon with chosen name
fixes https://github.com/mate-desktop/mate-control-center/issues/283

libslab: correct icon loading code

---

capplets/mouse/mate-mouse-properties.c
capplets/mouse/mate-mouse-properties.ui

libinput is the new default driver for touchpads and unlike the synaptics driver, it disables software buttons when clickfinger is enabled.
This commit introduces a warning message about this situation in the touchpad dialog. This message only appears when some multi-finger click emulation is enabled.
See https://bugzilla.redhat.com/show_bug.cgi?id=1465115
Thanks for considering it.

mouse: warn about enabling multi-finger emulation

---

capplets/appearance/appearance-desktop.c
typing-break/drw-break-window.c

avoid deprecated:
gdk_screen_get_monitor_geometry
gdk_screen_get_monitor_at_window

gtk 3.22: avoid deprecated gdk_screen_get_monitor... functions:

---

capplets/common/mate-theme-info.c

Hello all,
fix #308 
It could be useful for low-vision persons to be able to increase the size of the their cursors greater than 64. If the cursor theme doesn't provide cursor sizes greater than 64 the behavior is the same.
Best regards.

Add the support for cursor sizes of 96 and 128.

---

libslab/application-tile.c

If you have Ubuntu: check that all apps in m-c-c have localized names
If you don't have Ubuntu: check that all existing localizations in m-c-c are in place
fixes #239
fixes #260

fix support for external localizations in .desktop files

---

capplets/appearance/theme-installer.c
capplets/appearance/theme-util.c

fixes https://github.com/mate-desktop/mate-control-center/issues/322
Signed-off-by: Zhang Xianwei <zhang.xianwei8@zte.com.cn>
@raveit65

theme-util.c: fix reinstalling the deleted theme can cause failure

---

capplets/appearance/theme-installer.c

filetype is not used in mate_theme_install_real, remove it.

Remove useless parameter in mate_theme_install_real

---

capplets/about-me/mate-about-me-fingerprint.c
capplets/about-me/mate-about-me.c
capplets/appearance/appearance-desktop.c
capplets/appearance/appearance-themes.c
capplets/appearance/theme-installer.c
capplets/appearance/theme-util.c
capplets/common/capplet-stock-icons.c
capplets/common/file-transfer-dialog.c
capplets/common/theme-thumbnail.c
capplets/windows/mate-metacity-support.c
capplets/windows/mate-window-properties.c
font-viewer/font-view.c
typing-break/drwright.c

The expected with this PR: the same icons like before
Note: I think the translations are affected, so, this is not for 1.20

avoid deprecated GtkStock

---

capplets/display/xrandr-capplet.c

resolves #198 
The applet snaps to edges, but chooses the edge locations as if no displays are rotated. This patch fixes that by reading the rotated geometry where necessary.

Fix screen geometry to account for rotation when snapping.

---

capplets/appearance/appearance-style.c
capplets/common/mate-theme-info.c

The MATE cursor theme does not have an 18px cursor size, so having
a 18px as the default setting does not make sense. Using 24px looks
better in modern displays and allows for proper HiDPI scaling.
Relevant: mate-desktop/mate-desktop/pull/313

Change cursor-size to 24px

---

capplets/mouse/mate-mouse-properties.c
capplets/mouse/mate-mouse-properties.ui

Requested in https://github.com/mate-desktop/mate-applets/issues/261
Added a toggle into the Mouse widget that handles https://github.com/mate-desktop/mate-desktop/blob/master/schemas/org.mate.peripherals-mouse.gschema.xml.in#L28:
`Enables middle mouse button emulation through simultaneous left and right button click.`
<sub> Forgive me if there's anything wrong, please, it's my first contribution to such project. :]</sub>

Added middle mouse button emulation switch.

---

capplets/appearance/appearance-ui.c
capplets/appearance/appearance.h
capplets/appearance/data/appearance.ui

Requested in https://github.com/mate-desktop/mate-control-center/issues/346
Handles `org.mate.interface buttons-have-icons`

capplets/appearance: add buttons-have-icons switch

---

capplets/mouse/mate-mouse-properties.c
capplets/mouse/mate-mouse-properties.ui

Defaults to ON so as not to change expected behavior until user changes it.
Requires 
https://github.com/mate-desktop/mate-desktop/pull/332
and
https://github.com/mate-desktop/mate-settings-daemon/pull/234
Please test together

Mouse: include a toggle to enable or disable middlemouse paste

---

capplets/about-me/e-image-chooser.c
capplets/about-me/e-image-chooser.h
capplets/about-me/mate-about-me.c

Fixed EImageChooser's bug for mate-about-me, now it show fixed size image.
This bug can be found through testing:
For example, if you set different images one after another as user face, even if these images have the same size, they will still cause the displayed images to grow larger.
The follow image use the same file /usr/share/pixmaps/faces/book.jpg, but after change the user face  many times, it will show lager:
On the mate-about-me dialog, I think we should always show a fixed size picture.

Fixed image size

---

capplets/keybindings/01-desktop-key.xml.in

Provided additional "control-center" key binding.
For reference: https://github.com/mate-desktop/mate-settings-daemon/pull/244

keybindings: Add a key binding to launch settings

---

capplets/keybindings/mate-keybinding-properties.c

Seems `gtk_widget_ensure_style` is useless, according to the documentation:
https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-ensure-style
> Not a very useful function; most of the time, if you want the style, the widget is realized, and realized widgets are guaranteed to have a style already.

mate-keybinding-properties: avoid deprecated 'gtk_widget_ensure_style'

---

capplets/keybindings/mate-keybinding-properties.c

Closes https://github.com/mate-desktop/mate-control-center/issues/390

keybindings: double click instead one click to edit keyboard shortcuts

---

typing-break/drw-selection.c

Please review the code, thank you.

typing-break: replace deprecated gdk_error_trap functions

---

capplets/default-applications/mate-da-capplet.c

RTF files should be handled by the preferred word processor, just like ODF, DOC and OOXML.

default-applications: Use the selected word processor for RTF as well

---

capplets/default-applications/mate-da-capplet.c
capplets/default-applications/mate-da-capplet.h
capplets/default-applications/mate-default-applications-properties.ui

• Exposes a widget in Preferred Applications to control the default calculator application schema defined in commit https://github.com/mate-desktop/mate-desktop/pull/341/commits/328116089489c674bad3b17bc69c267865968d24
• In order to function properly, this PR is dependent on the merger of these two PRs:
1. https://github.com/mate-desktop/mate-desktop/pull/341
2. https://github.com/mate-desktop/mate-settings-daemon/pull/255
• Also fix https://github.com/mate-desktop/mate-control-center/issues/291

default-applications: Add a widget for a default calculator application

---

capplets/default-applications/mate-da-capplet.c

Prevent runtime failture on g_icon_to_string in fill_combo_box by catching the NULL case
See https://github.com/mate-desktop/mate-control-center/pull/398#issuecomment-445047978

default-applications: Fix assertion failture on g_icon_to_string

---

capplets/keybindings/eggcellrendererkeys.c

The expected, the same background color and font color in this widget:

eggcellrendererkeys: avoid deprecated 'gtk_widget_modify_bg/fg'

---

capplets/default-applications/mate-default-applications-properties.ui

Replace plain labels with frames as those properly group and label
their contents for assistive technologies.
There are no visual changes.

default-applications: Improve UI accessibility

---

capplets/appearance/appearance-themes.c
capplets/appearance/theme-installer.c
capplets/appearance/theme-installer.h
libwindow-settings/marco-window-manager.c

marco-window-manager.c:408:17: warning: Value stored to 'i' is never read
i = 0;
^   ~
theme-installer.c:813:3: warning: Value stored to 'filename' is never read
filename = old_folder;
^          ~~~~~~~~~~

Remove dead store detected by clang

---

capplets/appearance/data/appearance.ui

It adds two menu item separators, before and after of Print menu item.
Test:
- Run mate-appearance-properties
- Select Interface tab
- Click on File menu item
Before:
After:

Use GtkSeparatorMenuItem in Apparence preview

---

libslab/app-shell.h
shell/control-center.c

Reported by clang:
control-center.c:84:2: warning: Potential leak of memory pointed to by 'action'
g_slist_free(key_list);
^~~~~~~~~~~~

control-center: Fix memory leak

---

capplets/keybindings/Makefile.am
capplets/keybindings/mate-keybinding-properties.c

In [NixOS](https://nixos.org) packages are installed on their own directory, containing all needed files. For instance, on my current system `mate-control-center` keybindings are installed at `/nix/store/jxfznl8w38mqm5phrrsgfh8sv16dpnyw-mate-control-center-1.22.1/share/mate-control-center/keybindings/`, while `marco` keybindings are installed at `/nix/store/h0bvy5fczxik6akg58p8pxmqxg6jm9qs-marco-1.22.0/share/mate-control-center/keybindings/`.
As mate-control-center looks for keybinding shortcut files only on a single base directory, this becomes an [issue for NixOS](https://github.com/NixOS/nixpkgs/pull/60401). The window manager keybinding actions are not listed, because they are not found.
This PR changes mate control center to look for keybinding shortcut files in the system data dirs …

Use system data dirs to locate key bindings

---

capplets/default-applications/mate-da-capplet.c

The icon-name should be "image-x-generic" (imageviewer_image),
like "audio-x-generic" (media_player_image) and "video-x-generic"
(video_image).
Those icons (imageviewer_image, media_player_image,
video_image) are the generic mime types which can be opened
using its preferred application.
Before:
After:

Revert icon-name for imageviewer_image

---

configure.ac

The X server hasn't implemented it in over 10 years.
and it was dropped from debian since a long time.
fixes https://github.com/mate-desktop/mate-control-center/issues/481

drop libXxf86 dependency

---

font-viewer/mate-font-viewer.thumbnailer

shared-mime-info 1.9 and newer use font/ttf and font/otf as the mime types for OpenType and TrueType fonts.
This fixes font thumbnailing on Debian Buster, Ubuntu Bionic, Mint Tara and newer versions.
GNOME has a similar update.

font-viewer: Add font/ttf and font/otf mime types

---

font-viewer/mate-font-viewer.thumbnailer

We support collections but don't advertise the mimetype, so we fail
to lookup the correct thumbnailer.
origin commit:
https://gitlab.gnome.org/GNOME/gnome-font-viewer/commit/e1c54dd
This fixes creating thumbnail for e.g. google-noto-cjk fonts and warnings like this.
```
(mate-font-viewer:10706): MateDesktop-WARNING **: 15:59:02.209: Error creating thumbnail for file:///usr/share/fonts/google-noto-cjk/NotoSansCJK-Thin.ttc: Unrecognized image file format
(mate-font-viewer:10706): MateDesktop-WARNING **: 15:59:02.210: Unable to create loader for mime type font/collection: Unrecognized image file format
etc....
```

fv: thumbnailer: add font/collection to the supported mimetypes

---

capplets/about-me/mate-about-me-password.c

```
mate-about-me-password.c:39:5: warning: "__sun" is not defined, evaluates to 0 [-Wundef]
39 | #if __sun
|     ^~~~~
```

remove warning: "__sun" is not defined, evaluates to 0

---

libslab/mate-utils.c

Also scale properly for HiDPI displays
Before:
After:

icons: Force uniform size on icons

---

capplets/default-applications/mate-da-capplet.c

This helps them render sharply on HiDPI displays.

default-applications: Load icons as cairo surfaces

---

shell/matecc.desktop.in

Closes https://github.com/mate-desktop/mate-control-center/issues/512

shell: Fix typo in keyword name

---

capplets/appearance/data/Makefile.am

This fixes the contents of the first desktop file getting copied into the second.

appearance: Fix desktop file translation

---

capplets/keybindings/Makefile.am

This fixes the contents of the first schema file getting copied into the second.
This is a similar issue as I just fixed in https://github.com/mate-desktop/mate-control-center/commit/2aa9de5d86ceb7e21cecfe79d4c85626f2538c98 - might be worth for you guys to review all the makefiles touched in the gettext transition.

keybindings: Fix schema creation in makefile

---

capplets/about-me/e-image-chooser.c
libslab/app-resizer.c
libslab/nameplate-tile.c
libslab/search-bar.c
libslab/shell-window.c
libslab/themed-icon.c
typing-break/drw-break-window.c

Fixes the warnings:
```
e-image-chooser.c:76:44: warning: redundant redeclaration of ‘e_image_chooser_init’ [-Wredundant-decls]
e-image-chooser.c:76:44: warning: redundant redeclaration of ‘e_image_chooser_class_init’ [-Wredundant-decls]
app-resizer.c:31:28: warning: redundant redeclaration of ‘app_resizer_init’ [-Wredundant-decls]
app-resizer.c:31:28: warning: redundant redeclaration of ‘app_resizer_class_init’ [-Wredundant-decls]
nameplate-tile.c:48:44: warning: redundant redeclaration of ‘nameplate_tile_init’ [-Wredundant-decls]
nameplate-tile.c:48:44: warning: redundant redeclaration of ‘nameplate_tile_class_init’ [-Wredundant-decls]
search-bar.c:55:43: warning: redundant redeclaration of ‘nld_search_bar_init’ [-Wredundant-decls]
search-bar.c:55:43: warning: redundant redeclaration of …
```

avoid redundant redeclarations

---

capplets/common/gtkrc-utils.c
capplets/common/mate-theme-info.c

Currently `mate-control-center` does not use the mechanisms described in the [XDG Base Directory Specification](http://www.freedesktop.org/Standards/basedir-spec) to locate available themes. In this case the list of directories to look for system themes should be retrieved from the `XDG_DATA_DIRS` environment variable. But it is still using the deprecated function [`gtk_rc_get_theme_dir`](https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/deprecated/gtkrc.c#L805) (which uses the environment variable `GTK_DATA_PREFIX`).
This affects particularly the [NixOS](https://nixos.org/) package. See https://github.com/NixOS/nixpkgs/issues/75445.
This PR changes mate control center to look for system themes in the system data dirs (defined by the `XDG_DATA_DIRS` environment variable) and is …

Look for system themes in system data dirs

---

capplets/time-admin/src/time-share.c
capplets/time-admin/src/time-share.h

```
/usr/bin/ld: time-map.o:/home/robert/mate-control-center/capplets/time-admin/src/time-share.h:36: multiple definition of `TimeoutFlag'; main.o:/home/robert/mate-control-center/capplets/time-admin/src/time-share.h:36: first defined here
/usr/bin/ld: time-share.o:/home/robert/mate-control-center/capplets/time-admin/src/time-share.h:36: multiple definition of `TimeoutFlag'; main.o:/home/robert/mate-control-center/capplets/time-admin/src/time-share.h:36: first defined here
/usr/bin/ld: time-tool.o:/home/robert/mate-control-center/capplets/time-admin/src/time-share.h:36: multiple definition of `TimeoutFlag'; main.o:/home/robert/mate-control-center/capplets/time-admin/src/time-share.h:36: first defined here
/usr/bin/ld: time-zone.o:/home/robert/mate-control-center/capplets/time-admin/src/tim …
```

Fix build using gcc 10 -fno-common flag

---

capplets/about-me/Makefile.am
capplets/accessibility/at-properties/Makefile.am
capplets/appearance/Makefile.am
capplets/common/Makefile.am
capplets/default-applications/Makefile.am
capplets/display/Makefile.am
capplets/keybindings/Makefile.am
capplets/keyboard/Makefile.am
capplets/mouse/Makefile.am
capplets/network/Makefile.am
capplets/time-admin/src/Makefile.am
capplets/windows/Makefile.am
configure.ac
font-viewer/Makefile.am
libwindow-settings/Makefile.am
shell/Makefile.am
typing-break/Makefile.am

```shell
$ ./autogen.sh --enable-compile-warnings=maximum --enable-debug
<cut>
mate-control-center
Compiler:              gcc
Compiler flags:         -g -O0
Warning flags:         -Wall -Wmissing-prototypes -Wbad-function-cast -Wcast-align -Wextra -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wno-sign-compare
Linker flags:          
Appindicator:          yes
Libmate-slab:          yes
Accountsservice:       yes
Now type `make' to compile mate-control-center
<cut>
```

Compiler flags

---

capplets/about-me/Makefile.am
capplets/display/Makefile.am

`WARNING: Using --header and --body at the same time is deprecated; use --body --prototypes instead`

glib-genmarshal: Using --header and --body at the same time is deprecated

---

capplets/time-admin/src/time-zone.c

GCC 10 analyzer:
```
$ CFLAGS="-fanalyzer" ./autogen.sh --prefix=/usr && make
```
Warning:
```
In function ‘CreateCityList’:
time-zone.c:368:5: warning: dereference of NULL ‘db’ [CWE-690] [-Wanalyzer-null-dereference]
368 |     g_ptr_array_foreach (db->locations, (GFunc) LoadCities, ta->CityListStore);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
‘SetupTimezoneDialog’: events 1-2
|
|  461 | void SetupTimezoneDialog(TimeAdmin *ta)
|      |      ^~~~~~~~~~~~~~~~~~~
|      |      |
|      |      (1) entry to ‘SetupTimezoneDialog’
|......
|  505 |     CreateCityList(ta);
|      |     ~~~~~~~~~~~~~~~~~~
|      |     |
|      |     (2) calling ‘CreateCityList’ from ‘SetupTimezoneDialog’
|
+--> ‘CreateCityList’: events 3-4
|
|  363 | CreateCityList(TimeAdmin …
```

time-admin: dereference of NULL ‘db’ in function ‘CreateCityList’

---

capplets/windows/mate-window-properties.c

Test: `title_label_new` appears in the list of unused functions
```shell
$ CFLAGS="-pg" LDFLAGS="-pg" ./autogen.sh --prefix=/usr && make && sudo make install
$ cd capplets/windows/.libs
$ ./mate-window-properties
$ gprof -z ./mate-window-properties
```
Before:
```
Index by function name
[34] __do_global_dtors_aux  [14] capplet_help           [25] mouse_focus_toggled_callback
[35] __gmon_start__          [2] capplet_init           [26] register_tm_clones
[36] __libc_csu_fini        [15] capplet_set_icon        [4] reload_mouse_modifiers
[37] __libc_csu_init        [16] data_start              [5] resource_constructor
[38] _dl_relocate_static_pie [17] deregister_tm_clones  [27] resource_destructor
[39] _fini                  [18] directory_delete_recursive [28] response_cb
[40] _init …
```

windows: Remove unused function

---

capplets/appearance/appearance-themes.c

`mate_theme_meta_info_new ()` was called two times.
- `data->theme_custom = mate_theme_meta_info_new ();`
- `data->theme_custom = theme_load_from_gsettings (data);`
```shell
$ CFLAGS="-g -O0 -fsanitize=address" ./autogen.sh --prefix=/usr && make && sudo make install
$ mate-appearance-properties
```
```
Direct leak of 168 byte(s) in 1 object(s) allocated from:
#0 0x7f4e87b40e56 in __interceptor_calloc (/lib64/libasan.so.5+0x10de56)
#1 0x7f4e8648a3b0 in g_malloc0 (/lib64/libglib-2.0.so.0+0x573b0)
#2 0x42252f in themes_init /home/robert/sanitizer/mate-control-center/capplets/appearance/appearance-themes.c:1004
#3 0x41bf62 in main /home/robert/sanitizer/mate-control-center/capplets/appearance/appearance-main.c:182
#4 0x7f4e861271a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)
```

appearance: Fix memory leak

---

capplets/about-me/mate-about-me.c

Build & install:
```
$  CFLAGS="-g -O0 -fsanitize=address" ./autogen.sh --prefix=/usr && make V=1 && sudo make install
```
Run:
```
$ mate-about-me
```
Detected memory leak:
```
Direct leak of 7040 byte(s) in 1 object(s) allocated from:
#0 0x7f4566e66c58 in __interceptor_malloc (/lib64/libasan.so.5+0x10dc58)
#1 0x7f45657b0358 in g_malloc (/lib64/libglib-2.0.so.0+0x57358)
#2 0x414b8d in about_me_update_photo /home/robert/sanitizer/mate-control-center/capplets/about-me/mate-about-me.c:141
#3 0x415a37 in about_me_image_changed_cb /home/robert/sanitizer/mate-control-center/capplets/about-me/mate-about-me.c:358
#4 0x7f4565894741 in g_closure_invoke (/lib64/libgobject-2.0.so.0+0x13741)
```
Edit: Install the required libraries before Build & install:
```
```

mate-about-me: Fix memory leak

---

typing-break/drw-timer.c
typing-break/drw-timer.h

Test: Enable typing break on mate-keyboard-properties
Removed warnings:
```
drw-timer.c:26:2: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
26 |  GTimeVal start_time;
|  ^~~~~~~~
drw-timer.c:38:2: warning: ‘g_get_current_time’ is deprecated: Use 'g_get_real_time' instead [-Wdeprecated-declarations]
38 |  g_get_current_time (&timer->start_time);
|  ^~~~~~~~~~~~~~~~~~
drw-timer.c:43:2: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
43 |  GTimeVal now;
|  ^~~~~~~~
drw-timer.c:44:2: warning: ‘g_get_current_time’ is deprecated: Use 'g_get_real_time' instead [-Wdeprecated-declarations]
44 |  g_get_current_time (&now);
```

typing-break: Remove warning ‘GTimeVal’ is deprecated

---

libslab/double-click-detector.c
libslab/double-click-detector.h
libslab/libslab-utils.c
libslab/libslab-utils.h

Removed warnings:
```
libslab-utils.c:99:2: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
99 |  GTimeVal t_curr;
|  ^~~~~~~~
libslab-utils.c:101:2: warning: ‘g_get_current_time’ is deprecated: Use 'g_get_real_time' instead [-Wdeprecated-declarations]
101 |  g_get_current_time (& t_curr);
|  ^~~~~~~~~~~~~~~~~~
```

libslab: Remove libslab_get_current_time_millis

---

libslab/Makefile.am
libslab/bookmark-agent.c
libslab/libslab-utils.c
libslab/libslab-utils.h

Closes #554
test:
```shell
$ G_MESSAGES_DEBUG=libslab mate-control-center
(mate-control-center:98895): libslab-DEBUG: 12:03:52.651: Couldn't load bookmark file [NULL]
```
test 2:
```
$ mate-control-center 
$ cat ~/.xsession-errors
```

Port libslab_handle_g_error to the built-in GLib logging framework

---

capplets/appearance/appearance-main.c
capplets/windows/mate-window-properties.c

I forgot mate-window-properties to handle his notebook and add mouse tab scrolling.
I forgot too a secondary notebook in mate-appearance-properties (customize theme window).

Add tab scrolling support for GTK3

---

capplets/appearance/appearance-ui.c

```
appearance-ui.c:74:1: warning: ‘button_press_block_cb’ defined but not used [-Wunused-function]
74 | button_press_block_cb (GtkWidget *toolbar,
| ^~~~~~~~~~~~~~~~~~~~~
```

appearance-ui: Remove unused function button_press_block_cb

---

libslab/shell-window.c

```
shell-window.c:140:2: warning: ‘gtk_paint_flat_box’ is deprecated: Use 'GtkStyleContext and gtk_render_background' instead [-Wdeprecated-declarations]
140 |  gtk_paint_flat_box (
|  ^~~~~~~~~~~~~~~~~~
```

shell-window: deprecations and unused code

---

capplets/appearance/appearance-main.c
capplets/common/capplet-util.c
capplets/common/capplet-util.h
capplets/default-applications/mate-da-capplet.c
capplets/keyboard/mate-keyboard-properties.c
capplets/mouse/mate-mouse-properties.c
capplets/network/mate-network-properties.c
capplets/windows/mate-window-properties.c

Based on:
- https://github.com/mate-desktop/mate-terminal/commit/8d2eb0898154f2624e2ae34039169f307a3411a5
- https://github.com/mate-desktop/mate-terminal/commit/622e2d1272bf2d7a99d147482ae6a51b0a77f188

Remove unused variable from capplet_notebook_scroll_event_cb

---

capplets/common/mate-theme-apply.c
capplets/common/mate-theme-info.c
capplets/keybindings/eggcellrendererkeys.c
capplets/windows/mate-window-properties.c
font-viewer/font-view.c
libslab/app-shell.c
libslab/shell-window.c
libwindow-settings/marco-window-manager.c
typing-break/drwright.c

```
marco-window-manager.c:39: warning: macro "MARCO_USE_SYSTEM_FONT_KEY" is not used [-Wunused-macros]
39 | #define MARCO_USE_SYSTEM_FONT_KEY "titlebar-uses-system-font"
--
mate-theme-apply.c:34: warning: macro "FONT_KEY" is not used [-Wunused-macros]
34 | #define FONT_KEY                "font-name"
--
mate-theme-info.c:53: warning: macro "SOUND_THEME_KEY" is not used [-Wunused-macros]
53 | #define SOUND_THEME_KEY "X-GNOME-Metatheme/SoundTheme"
--
foo-marshal.c:3: warning: macro "__FOO_MARSHAL_MARSHAL_H__" is not used [-Wunused-macros]
3 | #define __FOO_MARSHAL_MARSHAL_H__
--
eggcellrendererkeys.c:12: warning: macro "N_" is not used [-Wunused-macros]
12 |   #define N_(x) x
--
mate-window-properties.c:43: warning: macro "MARCO_THEME_KEY" is not used [-Wunused-macros]
43 | #define …
```

Remove unused macros

---

capplets/keyboard/mate-keyboard-properties-a11y-notifications.ui
capplets/keyboard/ui-a11y.suppr

Fix a11y warnings by making the widget hierarchy more semantic, as well as making it saner (no more space-filled labels to create margins).  This rewrites a part of the dialog, but the only visual change is a slight difference in title margins due to using a stock `GtkFrame`.
Before
After

keyboard-properties-a11y-notifications.ui: Fix a11y warnings

---

capplets/default-applications/mate-da-capplet.c

From the default applications menu I changed the default application for audio, but didn't work for [FLAC](https://en.wikipedia.org/wiki/FLAC) audio files. This pull requests aims to solve that.
**Important**: I didn't compile it to test that it works, I have no experience with C and I got an error when I tried to execute `.autogen.sh`, I hope you can help me with your feedback if my changes don't work:
<pre><samp>
$ ACLOCAL_FLAGS="-I /usr/share/aclocal -I /usr/local/share/aclocal" ./autogen.sh
/usr/bin/mate-autogen
You need to install yelp-tools
checking for autoreconf >= 2.53...
testing autoreconf... found 2.69
checking for pkg-config >= 0.14.0...
testing pkg-config... found 0.29.1
checking for mate-common >= 1.1.0...
testing mate-doc-common... found 1.24.0
Checking for required M4 …

Default applications: Add flac format for media

---

capplets/windows/mate-window-properties.c
capplets/windows/window-properties.ui

This fixes some deprecations, adds the new settings
+Position and Behaviour: Show window-border in Alt-Tab
+Performance: Use reduced resources
and generally reorders the dialog.

mcc: windows-applet: Rewrite windows-properties.ui and add new settings.

---

libslab/application-tile.c

```
application-tile.c: In function 'update_user_list_menu_item':
application-tile.c:632:20: warning: suggest braces around empty body in an 'else' statement [-Wempty-body]
632 |   /* do nothing */ ;
|                    ^
```

application-tile: warning -Wempty-body

---

capplets/display/xrandr-capplet.c

```
xrandr-capplet.c: In function 'run_application':
/usr/include/glib-2.0/gobject/gtype.h:2297:6: warning: passing argument 1 of 'gtk_show_uri_on_window' from incompatible pointer type [-Wincompatible-pointer-types]
2297 |     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
/usr/include/glib-2.0/gobject/gtype.h:484:66: note: in expansion of macro '_G_TYPE_CIC'
484 | #define G_TYPE_CHECK_INSTANCE_CAST(instance, g_type, c_type)    (_G_TYPE_CIC ((instance), (g_type), c_type))
|                                                                  ^~~~~~~~~~~
/usr/include/gtk-3.0/gtk/gtkdialog.h:90:43: note: in expansion of macro 'G_TYPE_CHECK_INSTANCE_CAST'
90 | #define GTK_DIALOG(obj)                  (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_DIALOG, GtkDialog))
| …
```

xrandr-capplet: warning -Wincompatible-pointer-types

---

capplets/windows/mate-window-properties.c
capplets/windows/window-properties.ui

The design is more similar to the original now.
Adds allow-top-tiling option, which is insensitive if use-reduced-resources is true or if allow-tiling (Enable window tiling) is false.

Revisit windows applet, add allow-top-tiling option

---

configure.ac

Test:
```
$ ./autogen.sh --prefix=/usr
<cut>
Configure summary:
mate-control-center 1.25.0
==========================
Compiler:              gcc
Compiler flags:        
Warning flags:         -Wall -Wmissing-prototypes
Linker flags:          
Appindicator:          yes
Libmate-slab:          yes
Accountsservice:       yes
Now type `make' to compile mate-control-center
```

build: show the package version in the configure summary

---

capplets/common/gtkrc-utils.c

Fix the warnings below:
```
gtkrc-utils.c:37:8: warning: no previous prototype for ‘gtkrc_find_named’ [-Wmissing-prototypes]
gtkrc-utils.c:82:6: warning: no previous prototype for ‘gtkrc_get_details’ [-Wmissing-prototypes]
gtkrc-utils.c:179:1: warning: no previous prototype for ‘gtkrc_get_color_scheme’ [-Wmissing-prototypes]
gtkrc-utils.c:243:8: warning: no previous prototype for ‘gtkrc_get_color_scheme_for_theme’ [-Wmissing-prototypes]
```

common: missing include gtkrc-utils.h

---

capplets/windows/mate-metacity-support.c

Fix the warning below:
```
mate-metacity-support.c:30:1: warning: no previous prototype for ‘mate_metacity_config_tool’ [-Wmissing-prototypes]
```

windows: missing include mate-metacity-support.h

---

libwindow-settings/marco-window-manager.h

Fix the warning below:
```
marco-window-manager.c:87:1: warning: no previous prototype for ‘window_manager_new’ [-Wmissing-prototypes]
```

libwindow-settings: no previous prototype for ‘window_manager_new’

---

capplets/appearance/appearance-desktop.c
capplets/appearance/appearance-font.c
capplets/appearance/appearance-style.c
capplets/appearance/appearance-support.c
capplets/appearance/appearance-themes.c
capplets/appearance/appearance-ui.c
capplets/appearance/mate-wp-xml.c

Fix the warnings below:
```
appearance-ui.c:74:1: warning: no previous prototype for ‘ui_init’ [-Wmissing-prototypes]
appearance-style.c:987:1: warning: no previous prototype for ‘style_init’ [-Wmissing-prototypes]
appearance-style.c:1055:1: warning: no previous prototype for ‘style_shutdown’ [-Wmissing-prototypes]
appearance-font.c:732:6: warning: no previous prototype for ‘font_init’ [-Wmissing-prototypes]
appearance-font.c:799:6: warning: no previous prototype for ‘font_shutdown’ [-Wmissing-prototypes]
appearance-themes.c:976:6: warning: no previous prototype for ‘themes_init’ [-Wmissing-prototypes]
appearance-themes.c:1136:1: warning: no previous prototype for ‘themes_shutdown’ [-Wmissing-prototypes]
appearance-desktop.c:609:1: warning: no previous prototype for …
```

appearance: -Wmissing-prototypes warnings

---

libwindow-settings/marco-window-manager.c

based on marco code https://github.com/mate-desktop/marco/blob/7ab70915e515337e9900809ddaf404f8d57622ec/src/ui/theme-parser.c#L4395-L4418

marco-window-manager: get XDG_DATA_DIRS (code portability)

---

capplets/windows/Makefile.am

Test:
```
$ git grep UIDIR
$ git grep PIXMAPDIR
```

windows: remove unused macros UIDIR, PIXMAPDIR

---

capplets/display/display-capplet.ui
capplets/display/ui-a11y.suppr
capplets/display/xrandr-capplet.c

This PR adds a new feature to the display preferences interface,This new feature adjusts the scaling of the window.
But please note that the adjustment of the window scale is real-time. When you select the scale, the window will start to change immediately
```
mate-display-properties
adjust window scaling
```

Add adjust window scaling function for display preferences

---

capplets/display/mate-display-properties-install-systemwide.c
capplets/display/scrollarea.c
capplets/display/xrandr-capplet.c

```
xrandr-capplet.c:326:19: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
xrandr-capplet.c:379:10: warning: conversion to ‘int’ from ‘guint’ {aka ‘unsigned int’} may change the sign of the result [-Wsign-conversion]
xrandr-capplet.c:380:11: warning: conversion to ‘int’ from ‘guint’ {aka ‘unsigned int’} may change the sign of the result [-Wsign-conversion]
xrandr-capplet.c:571:6: warning: conversion to ‘int’ from ‘guint’ {aka ‘unsigned int’} may change the sign of the result [-Wsign-conversion]
xrandr-capplet.c:572:6: warning: conversion to ‘int’ from ‘guint’ {aka ‘unsigned int’} may change the sign of the result [-Wsign-conversion]
xrandr-capplet.c:611:10: warning: conversion to ‘int’ from ‘guint’ {aka ‘unsigned int’} …
```

display: remove conversion warnings

---

capplets/time-admin/src/time-zone.c

Fedora 34 beta bundles glib2 2.68.0:
```
$ cat /etc/redhat-release 
Fedora release 34 (Thirty Four)
$ rpm -q --qf "%{VERSION}\n" glib2
2.68.0
```
Compiler warning:
```
time-zone.c: In function ‘update_timezone’:
time-zone.c:299:5: warning: ‘g_time_zone_new’ is deprecated: Use 'g_time_zone_new_identifier' instead [-Wdeprecated-declarations]
299 |     timezone = g_time_zone_new (current_location->zone);
|     ^~~~~~~~
```
https://developer.gnome.org/glib/stable/glib-GTimeZone.html#g-time-zone-new

time-admin: g_time_zone_new is deprecated from glib 2.68

---

capplets/windows/mate-window-properties.c
capplets/windows/window-properties.ui

in a way it makes more sense. The alt-tab options are now grouped together. The "Compositing Manager" tab is now the "Performance" tab, which is better because there can be added more options in the future such as "disable animations".

windows-applet: group alt-tab options, remove reduced-resources option

---

capplets/windows/mate-window-properties.c
capplets/windows/window-properties.ui

Fixes #640 
**Updated:**
The possible values for titlebar buttons positions are now: Right (with menu), Left (with menu), Right, Left.
With this PR, if the user altered the value via dconf-editor or mate-tweak or in another way to a different value, mcc does not overwrite this setting.
Test:
change marco->general->button-layout in dconf to an arbitrary value.
With PR the gsettings value is respected (not overwritten) when opening the windows applet from mcc.
**Update 2:**
csd windows respect the titlebar button layout as well, (see https://github.com/mate-desktop/mate-control-center/pull/574)

windows-applet: add custom titlebar button layout option

---

capplets/display/display-capplet.ui

Use gtk-cancel icon replace window-close icon，Icons belong to the same category, which is more beautiful and harmonious
Fix #648

Use gtk-cancel icon replace window-close icon

---

capplets/about-me/mate-about-me-password.c
capplets/keyboard/mate-keyboard-properties-xkb.c
capplets/keyboard/mate-keyboard-properties-xkbltadd.c
font-viewer/font-view.c

Fixed some compilation warnings that there were ``` no previous prototypes [- wmissing prototypes]```
We still have a lot to do. There are too many outdated APIs that we need to replace

Fix compilation warning

---

libslab/tile.c

```gtk_button_released``` has been deprecated, and we don't need to send signals manually

Remove useless and discarded gtk_button_released

---

libslab/app-resizer.c
libslab/app-resizer.h
libslab/app-shell.c

Reduce compilation warnings 
Replace the deprecated GtkTable with GtkGrid
The display effect is the same as before, and there is no warning at runtime

Replace the deprecated GtkTable with GtkGrid

---

libslab/bookmark-agent.c

g_bookmark_file_set_modified_date_time is used in libslab/bookmark-agent.c which sets the last time the bookmark for uri was last modified.
g_bookmark_file_set_modified_date_time is only available in GLib 2.66 and newer.

Maintain compatibility with GLib versions older than 2.66. Fixes #655

---

capplets/time-admin/src/main.c

These specific functions can only cause mess when translated, it's better to keep the original terms.

Remove redundant i18n strings

---

capplets/about-me/mate-about-me-password.c

g_queue_clear_full() is only available since glib 2.60; using
g_queue_free_full() allows not to bump the glib version requirement
too much (it’s been introduced in 2.32).

GLib compatibility: use g_queue_free_full() instead of g_queue_clear_full()

---

capplets/appearance/appearance-main.c
capplets/default-applications/mate-da-capplet.c
capplets/keybindings/eggcellrendererkeys.c
capplets/keyboard/mate-keyboard-properties.c
capplets/mouse/mate-mouse-properties.c
font-viewer/font-thumbnailer.c
font-viewer/font-view.c
shell/control-center.c
typing-break/drw-monitor.c
typing-break/main.c

```
appearance-main.c:163:14: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL }
^
--
mate-da-capplet.c:785:8: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{NULL}
^
--
mate-keyboard-properties.c:181:8: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{NULL}
^
--
eggcellrendererkeys.c:70:3: warning: missing field 'value_table' initializer [-Wmissing-field-initializers]
};
^
--
eggcellrendererkeys.c:525:7: warning: missing field 'value_table' initializer [-Wmissing-field-initializers]
};
^
--
mate-mouse-properties.c:402:8: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{NULL}
^
--
font-thumbnailer.c:199:13: warning: missing field 'short_name' initializer …
```

Fix build warnings about missing field initializer

---

capplets/appearance/appearance-style.c

```
LeakSanitizer: detected memory leaks
Direct leak of 8 byte(s) in 1 object(s) allocated from:
#0 0x7fa87bee293f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7fa87a7c0b7f in g_malloc ../glib/gmem.c:106
#2 0x7fa87a7c0ec2 in g_malloc_n ../glib/gmem.c:344
#3 0x7fa87a7e31a5 in g_strdup ../glib/gstrfuncs.c:364
#4 0x43c306 in gtk_theme_info_missing_engine /home/robert/builddir.gcc/mate-control-center/capplets/common/mate-theme-info.c:1401
#5 0x424548 in update_message_area /home/robert/builddir.gcc/mate-control-center/capplets/appearance/appearance-style.c:216
#6 0x4290dd in style_init /home/robert/builddir.gcc/mate-control-center/capplets/appearance/appearance-style.c:1052
#7 0x41be9b in main /home/robert/builddir.gcc/mate-control-center/capplets/appearance/appearance-main.c:176 …
```

appearance-style: fix memory leak

---

libslab/bookmark-agent.c

Test:
```
grep -R -w "^[[:space:]]*#if\|^[[:space:]]*#else\|[[:space:]]*#endif" --include *.c
```

bookmark-agent: remove whitespaces before #if, #else, and #endif

---

capplets/keyboard/mate-keyboard-properties-xkbmc.c

```
CFLAGS="-ggdb3 -O0 -fsanitize=address" LDFLAGS="-fsanitize=address" ./autogen.sh --prefix=/usr && make && sudo make install
```
```
Direct leak of 1263 byte(s) in 133 object(s) allocated from:
#0 0x7fdec0b3f93f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7fdebf2274df in g_malloc ../glib/gmem.c:106
#2 0x7fdebf227822 in g_malloc_n ../glib/gmem.c:344
#3 0x7fdebf249e35 in g_strdup ../glib/gstrfuncs.c:361
#4 0x7fdebf369016 in value_lcopy_string ../gobject/gvaluetypes.c:313
#5 0x7fdebff838fc in gtk_tree_model_get_valist ../gtk/gtktreemodel.c:1812
#6 0x7fdebff8334b in gtk_tree_model_get ../gtk/gtktreemodel.c:1774
#7 0x4099e0 in gtk_list_store_find_entry /home/robert/builddir.gcc/mate-control-center/capplets/keyboard/mate-keyboard-properties-xkbmc.c:54
#8 0x409c39 in …
```

keyboard: fix memory leak

---

capplets/common/mate-theme-info.c
libwindow-settings/marco-window-manager.c

```
CFLAGS="-Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
```
marco-window-manager.c:290:39: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
settings->autoraise = g_settings_get_boolean (meta_wm->p->settings,
~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--
mate-theme-info.c:729:29: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
theme_info->has_gtk = theme_exists;
~ ^~~~~~~~~~~~
mate-theme-info.c:732:36: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion] …
```

Fix implicit conversion changes signedness: 'gboolean' to 'guint'

---

capplets/windows/window-properties.ui

Trivial fix for inconsistent spacing in the *Compositing Manager* tab, which was 1px bigger than the other tabs (and 13 is an unusual amount, where 12 is a common one)

windows: Fix spacing in the Compositing Manager tab

---

capplets/windows/mate-window-properties.c
capplets/windows/window-properties.ui

Use real frames for a semantic UI so GTK and screen readers can set up and figure out accessibility relationships between the frame label and the content automatically.
Also properly add relationships between the movement keys descriptive label and the key radio items so a screen reader can pick it up.  As a bonus, it also prevents Orca from erroneously announcing the label when the window comes up because it thinks this long orphaned label is probably a general description for the window.
Fixes #703.

windows: Fix UI accessibility

---

libslab/app-shell.c

*This permits the control center to run on wayland and simplifies to code

Wayland: remove Xorg-only code from screen width detection

---

.build.yml
capplets/Makefile.am
capplets/system-info/Makefile.am
capplets/system-info/info-cleanup.c
capplets/system-info/info-cleanup.h
capplets/system-info/main.c
capplets/system-info/mate-system-info.c
capplets/system-info/mate-system-info.desktop.in
capplets/system-info/mate-system-info.h
capplets/system-info/mate-system-info.ui
capplets/system-info/system-info.gresource.xml
configure.ac
org.mate.control-center.gschema.xml.in
po/POTFILES.in

Other desktops offer this feature, and we should also add it. I use the ```MATE desktop```, but every time I display system information, I have to open the ```gnome-control-center info-overview```

Add new capplets: system info

---

capplets/appearance/Makefile.am
capplets/appearance/appearance-themes.c

```appearance``` is no need to call ```match_wm_manager_init``` because we no longer use ```match_wm_manager_get_current``` and ```match_wm_manager_spawn_config_tool_for_current```, This is a useless initialization
Similarly, ```libwindow-settings``` is an outdated and unnecessary API that has not been called by any project

appearance: Remove useless match_wm_manager_init function

---

capplets/appearance/appearance-desktop.c
capplets/appearance/theme-installer.c

```g_pattern_match_string``` has been deprecated since GLib 2.70

appearance: Fix compilation warnings replace deprecated functions

---

capplets/time-admin/src/meson.build

*Ensure we attempt to load files from `mate-time-admin/map/ `not ` mate-time-admin/map`
*Otherwise mate-time-admin built with meson cannot find the files and errors out, crashing on an attempt to load (with /usr/share/  as  data directory`)/usr/share/mate-time-admin/mapbackward `instead of 
`/usr/share/mate-time-admin/map/backward`

Meson: fix mate-time-admin directory error

---

Makefile.am

Proper testing instructions:
Generate a tarball with `./autogen.sh && make && make dist`
Extract the tarball
cd mate-control-center-1.28.0/
meson setup build -Dprefix=/usr/local
ninja -C build
sudo ninja -C build install
sudo ninja -C build uninstall

Distribute Meson build system

---

.build.yml
capplets/system-info/mate-system-info.c
configure.ac

There is not much of direct systemd usage in the system-info plugin. This patch suggestion enables building this plugin on system like alpine, voidlinux or gentoo with openrc.
I apologize in advance if this seems sloppy. I am not very knowledgeable with autotools (also, this patch excludes meson).
Suggestions on how to improve the patch are most welcome.

Make systemd optional

---

capplets/Makefile.am

time-admin depends on systemd. If systemd is not used in the systemd, time-admin is disabled

Add time-admin dependency check on systemd

---

capplets/appearance/appearance-style.c

Since wayland compositors such as wayfire follow the GNOME interface gsettings values, we need to set them here too.
*Otherwise we can only reliably select existing metathemes or sometimes a saved custom theme.

appearance under wayland: fix customizing themes

---

capplets/time-admin/src/time-zones.h

https://en.wikipedia.org/wiki/KyivNotKiev

Update time-zones.h Kiev->Kyiv

---

mate-control-center.pot

https://en.wikipedia.org/wiki/KyivNotKiev

Update mate-control-center.pot Kiev->Kyiv

---

capplets/keybindings/eggcellrendererkeys.c
capplets/keybindings/mate-keybinding-properties.ui

* Hint to the keyboard navigation in the help text
* Present something to the screen reader when waiting for a new shortcut
* Fix the value screen readers see for the shortcut of group rows (which is visually empty, but had seemingly random values for the screen readers)
@joanmarie @shindere Hope that fixes https://www.freelists.org/post/orca/Could-Orca-be-more-accurate-in-the-keyboard-shortcut-system-window,4  Could you give it a spin?
However, I couldn't seem to get the help-text stuff to work, even with Orca 48/AT-SPI 2.56 from Debian Bookworm's backports.
I hope the updated help text and tooltip are enough; and there's an additional fix for group rows.

Improve accessibility of the keybindings properties dialog

---

capplets/keyboard/mate-keyboard-properties-dialog.ui
capplets/keyboard/mate-keyboard-properties-xkb.c

- add new checkbox "Include less-common layouts in the selections list" 
- switch /org/mate/desktop/peripherals/keyboard/general/load-extra-items
- it is a port/re-work of https://github.com/linuxmint/cinnamon-control-center/commit/d961517fd248f62dc1dc8040731c48822dd68891#diff-7525274c9dc606950625f46b7d8150e4223d7ad4eb9fae59d700d45539c4ccddR196
purpose of the feature. 
it is really hard to know what option controls that extra layout list, I had spent hours groking why my laptop can show them and desktop can't 
so probably it will be useful for newbies and such 
P.S. please be extra careful with review - this is my first ever PR into gtk/mate code

keyboard: option to show/select extra layouts

---

font-viewer/font-view.c

If the app is already open, we need to tell the desktop that the window has been triggered, so it can either bring it to front, or notify the user the window claims attention.
This fixes the cases where the font viewer is already open and gets triggered again, e.g. by opening a font or launching it directly.

font-viewer: Bring the window to the front when triggering the app

---

capplets/default-applications/mate-default-applications-properties.ui

This old PR align bottom spacing between _notebook_ & _buttons_ for **mate-default-applications-properties** like in **mate-appearance-properties**.
before:
---
after:

Update window layout
